"""reminder notifications

Revision ID: 095941a20484
Revises: 35302def4575
Create Date: 2026-09-29 11:47:50.236525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '095941a20484'
down_revision: Union[str, Sequence[str], None] = '35302def4575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('item', sa.String(length=128), nullable=False),
    sa.Column('sent_on', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_id', 'item', 'sent_on', name='uq_reminder_once_per_day')
    )
    op.create_index(op.f('ix_reminder_notifications_entity_id'), 'reminder_notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reminder_notifications_user_id'), 'reminder_notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_notifications_user_id'), table_name='reminder_notifications')
    op.drop_index(op.f('ix_reminder_notifications_entity_id'), table_name='reminder_notifications')
    op.drop_table('reminder_notifications')
    # ### end Alembic commands ###
