"""slack user link

Revision ID: 84d17e5b5901
Revises: 095941a20484
Create Date: 2026-09-29 11:59:54.502327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d17e5b5901'
down_revision: Union[str, Sequence[str], None] = '095941a20484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slack_user_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['slack_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'slack_user_id')
    # ### end Alembic commands ###
