"""blob filename

Revision ID: ba2c8c4f76cd
Revises: 84d17e5b5901
Create Date: 2026-09-29 12:24:39.524049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2c8c4f76cd'
down_revision: Union[str, Sequence[str], None] = '84d17e5b5901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blobs', sa.Column('filename', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blobs', 'filename')
    # ### end Alembic commands ###
